"""
Given an array of strings, group anagrams together.

Example:

Input: ["eat", "tea", "tan", "ate", "nat", "bat"],
Output:
[
  ["ate","eat","tea"],
  ["nat","tan"],
  ["bat"]
]
Note:

All inputs will be in lowercase.
The order of your output does not matter.
https://leetcode.com/problems/group-anagrams/
"""
class Solution(object):
    def groupAnagrams(self, strs):
        final_dict = {}
        for word in strs:
            key = ''.join(sorted(word))
            if key not in final_dict:
                final_dict[key] = [word]
            else:
                final_dict[key].append(word)
        return final_dict.values()


if __name__ == '__main__':
    sol = Solution()
    print(sol.groupAnagrams(
        ["nozzle", "punjabi", "waterlogged", "imprison", "crux", "numismatists", "sultans", "rambles", "deprecating",
         "aware", "outfield", "marlborough", "guardrooms", "roast", "wattage", "shortcuts", "confidential", "reprint",
         "foxtrot", "dispossession", "floodgate", "unfriendliest", "semimonthlies", "dwellers", "walkways", "wastrels",
         "dippers", "engrossing", "undertakings", "unforeseen", "oscilloscopes", "pioneers", "geller", "neglects",
         "cultivates", "mantegna", "elicit", "couriered", "shielded", "shrew", "heartening", "lucks", "teammates",
         "jewishness", "documentaries", "subliming", "sultan", "redo", "recopy", "flippancy", "rothko", "conductor",
         "e", "carolingian", "outmanoeuvres", "gewgaw", "saki", "sarah", "snooping", "hakka", "highness", "mewling",
         "spender", "blockhead", "detonated", "cognac", "congaing", "prissy", "loathes", "bluebell", "involuntary",
         "aping", "sadly", "jiving", "buffalo", "chided", "instalment", "boon", "ashikaga", "enigmas", "recommenced",
         "snell", "parsley", "buns", "abracadabra", "forewomen", "persecuted", "carsick", "janitorial", "neonate",
         "expeditiously", "porterhouse", "bussed", "charm", "tinseled", "pencils", "inherits", "crew", "estimate",
         "blacktop", "mythologists", "essequibo", "dusky", "fends", "pithily", "positively", "participants", "brew",
         "tows", "pentathlon", "misdiagnoses", "paraphrase", "telephoning", "engining", "anglo", "duisburg",
         "shorthorns", "physical", "enquiries", "grudging", "floodlit", "safflower", "asphalts", "representing",
         "airbrush", "bedevilling", "fulminations", "peacefuller", "hurl", "unequalled", "wiser", "vinson", "paglia",
         "doggones", "optimist", "rulering", "katmandu", "flutists", "sterling", "oregonians", "boosts", "slaver",
         "straightedges", "stendhal", "defaulters", "stylize", "chucking", "adulterate", "partaking", "omelettes",
         "monochrome", "bitched", "foxhound", "tapir", "vocalizing", "manifolding", "northerner", "ineptly", "dunce",
         "matchbook", "locutions", "docudrama", "sinkers", "paralegal", "sip", "maliced", "lechers", "zippy", "tillman",
         "penknives", "olympias", "designates", "mossiest", "leanne", "lavishing", "understate", "underwriting",
         "showered", "belittle", "propounded", "gristly", "toxicity", "trike", "baudelaire", "sheers", "annmarie",
         "poultices", "therapeutics", "inputs", "bailed", "minutest", "pynchon", "jinx", "jackets", "subsections",
         "harmonizes", "caesareans", "freshened", "haring", "disruption", "buckle", "per", "pined", "solemnity",
         "recombined", "chamber", "tangling", "pitiful", "authoritarians", "oort", "ingratiate", "refreshed",
         "bavarian", "generically", "rescheduled", "typewritten", "level", "magnetism", "socialists", "oligocene",
         "resentful", "lambast", "counteroffer", "firefight", "phil", "attenuates", "teary", "demarcated", "moralities",
         "electrified", "pettiness", "unpacking", "hungary", "heavies", "tenancies", "tirade", "solaria", "scarcity",
         "prettiest", "carrillo", "yodel", "cantilever", "ridiculously", "tagalog", "schismatics", "ossification",
         "hezbollah", "downscaling", "calking", "tapped", "girl", "alba", "lavishness", "stepparents", "integrator",
         "overact", "father", "fobbing", "pb", "require", "toes", "sweats", "prisoners", "mbabane", "hatch", "motleyer",
         "worlds", "decentralize", "ingrained", "shekels", "directorship", "negotiating", "hiawatha", "busying",
         "reciprocate", "spinsterhood", "supervened", "scrimmage", "decolonized", "buildups", "sedative", "swats",
         "despotic", "driblets", "redoubting", "stoic", "xeroxes", "satellited", "exteriors", "deregulates", "lawful",
         "flunk", "broached", "energetics", "moodily", "popinjays", "shoshone", "misleads", "abduct", "nonevent",
         "flees", "harry", "cleverness", "manipulative", "shoplifts", "tom", "junk", "poniard", "transmute", "stricter",
         "trochees", "snack", "relations", "edger", "culminate", "implication", "carjacked", "kissers", "federate",
         "offsetting", "sutures", "wakened", "axis", "boxcars", "grinds", "scenting", "cordoba", "lumberyards",
         "incendiary", "antiphonal", "decipherable", "gilliam", "redecorates", "plum", "nitpickers", "linefeed",
         "awakes", "embittering", "spewing", "annul", "filial", "scarlet", "connors", "sanctum", "scotsman", "isobar",
         "activity", "overthrowing", "unseasoned", "tarantulae", "outtake", "diego", "mars", "stunted", "hunted",
         "sublimation", "barbadian", "barbarisms", "epidemic", "assesses", "imposture", "freaks", "detroit",
         "bloodiest", "avails", "prenatal", "connecticut", "guardsmen", "betwixt", "windsock", "neutralized",
         "psychoanalysis", "rubberized", "overproduces", "narcissism", "tallow", "cringes", "resinous", "paintbrushes",
         "duality", "paints", "deactivated", "expertly", "speedsters", "coward", "bass", "psychiatrist", "curies",
         "betrays", "bubble", "mellow", "showy", "retarding", "radishes", "coy", "unreservedly", "larks", "apportioned",
         "flaccid", "relabelling", "alphabeted", "anointment", "helms", "gillian", "trophying", "breakage",
         "underbrush", "directest", "wingtips", "pretence", "preshrink", "remarries", "addle", "brouhaha", "mobbing",
         "g", "dings", "gains", "stockade", "ouch", "particulates", "listens", "habituation", "kill", "crouped",
         "hyperbolae", "hutching", "stoney", "rightness", "davids", "questioned", "ethiopians", "courtliness", "delays",
         "navahos", "devils", "keeling", "accelerators", "investigator", "spindling", "illegality", "extremer",
         "revlon", "purity", "bradly", "jut", "machs", "liquidated", "informant", "smartly", "disfigure", "parliaments",
         "croup", "teletypes", "impression", "trainee", "implications", "embed", "podiatrists", "jewelled",
         "brokenhearted", "spaceman", "unsteadier", "kitchen", "twirling", "conurbations", "pygmies", "lourdes",
         "watertight", "reassessing", "dempsey", "matriarch", "alas", "abscissae", "decanter", "commentated", "sandy",
         "idler", "soybean", "cutoff", "dictate", "credibility", "indeterminable", "release", "blank", "curitiba",
         "pericardia", "probably", "indisposition", "hesitantly", "duff", "ratty", "derivative", "decals",
         "explication", "cockier", "monoxides", "hyperventilate", "genially", "polluter", "divan", "may", "convalesces",
         "morpheme", "pupa", "prospered", "tagging", "nerdier", "detached", "spearing", "hilbert", "russeted",
         "amanuensis", "periwinkles", "jujube", "guarantors", "premises", "descanting", "baned", "deviance", "sidearms",
         "lamentable", "barristers", "climes", "succulence", "mauve", "oceanographers", "migraine", "bisexual",
         "peruvians", "fatheads", "parsimony", "pilaf", "portly", "conniving", "insidiously", "inventing",
         "constabulary", "cling", "stunting", "accessioned", "deadliness", "overthrow", "expectorant", "agamemnon",
         "blindfold", "striker", "shrugging", "jibes", "appropriateness", "annihilates", "hairs", "proselytes", "goads",
         "rankling", "predominated", "hart", "enemies", "culpability", "drank", "martinets", "prospering", "dominick",
         "complemented", "invention", "foolscap", "tolerances", "lorelei", "profits", "awarer", "ungodlier",
         "victoriously", "mistrusts", "princes", "drudge", "moderator", "transversed", "disco", "japed", "loomed",
         "incense", "ponds", "gumbel", "disarranges", "coaxes", "technology", "hyde", "debentures", "confidantes",
         "hankered", "savant", "styes", "croupy", "unapproachable", "cisterns", "unto", "duds", "conglomerating",
         "clio", "negroid", "looked", "methodism", "hilario", "balloon", "thesauruses", "integuments", "thermometer",
         "slacks", "wigwagging", "gaping", "incensed", "misquotes", "chocking", "patrols", "upcoming", "insists",
         "livings", "thoth", "uselessness", "vibrated", "potluck", "starboard", "uniquer", "boone", "scintillates",
         "darker", "massey", "arbitrariness", "miniaturized", "rousseau", "chiffon", "consortia", "coral", "finesses",
         "half", "biked", "unlikeliest", "hilarious", "acrid", "twinkles", "galileo", "outsmarted", "ostentation",
         "cradle", "frats", "misidentifies", "uncleaner", "bacardi", "smoothest", "antwan", "warren", "jingling",
         "stocks", "daumier", "paranoid", "pantaloons", "dishing", "receive", "underpays", "kane", "variation", "beset",
         "disobliged", "dreadlocks", "psychics", "twofers", "lieutenants", "pebbling", "interposes", "shingles",
         "profanes", "machining", "dysfunctions", "wolfram", "brut", "nebraskan", "truculently", "copeland", "devonian",
         "fuller", "silvia", "philosophers", "cali", "adores", "disquiet", "savvies", "minatory", "blooms",
         "radiotelephones", "paradoxically", "competitions", "gandhi", "weddell", "occludes", "retracing", "kari",
         "dead", "lagoons", "menfolk", "abundant", "enacts", "conferences", "procreation", "steadier", "cols", "rabble",
         "unquestioned", "stupefying", "whodunit", "dizzier", "paula", "riposte", "elixirs", "discontented",
         "zimbabweans", "assemblage", "unsalted", "genders", "caldwell", "pulleys", "pureness", "kingston", "vests",
         "hearken", "abuses", "scull", "hussar", "solace", "gondwanaland", "surfacing", "vivienne", "subculture",
         "reciprocal", "expediencies", "projectiles", "segregationist", "prickle", "pooped", "telecommutes", "axes",
         "scenery", "peppery", "parenthesizing", "checked", "trademarked", "unreasonable", "curtly", "dynamically",
         "vulcanize", "airtight", "blotch", "edmund", "stoicism", "scrambles", "whirled", "chasing", "millstones",
         "helplessly", "permalloy", "remanding", "duplicate", "broadsided", "readjustment", "buggers", "quaked",
         "grapples", "democrats", "landfalls", "apprehensively", "turmoiling", "railing", "lothario", "modishly",
         "faggoted", "deflecting", "interment", "dodo", "recreants", "baywatch", "frescoes", "temblor", "brigade",
         "handgun", "bradstreet", "caspar", "godsend", "cochleae", "queered", "unevenness", "hairnet", "millimeters",
         "flawless", "plumbing", "disciplinarian", "orbiting", "foothill", "serviettes", "peseta", "windmills",
         "myrdal", "provides", "slowdowns", "clouting", "gainsays", "dishpans", "mediates", "weaker", "shoestrings",
         "gerunds", "potsdam", "chips", "disqualifications", "focus", "quarry", "dwarfs", "laurels", "coverall",
         "reconsidered", "exploded", "distending", "bronzes", "apollonian", "sweeper", "couperin", "gourmets",
         "irreconcilable", "goldbricking", "emotes", "demilitarizes", "lambkin", "grouper", "anyways", "hugs",
         "quizzed", "misstatement", "spectrums", "frigates", "plenipotentiaries", "parasites", "tacitly", "savvying",
         "treks", "dissociating", "departing", "resins", "psychiatric", "tablespoonfuls", "aught", "makeup", "copping",
         "interwove", "selling", "fantasize", "flamingos", "smolders", "stript", "laverne", "extremely", "chattering",
         "imminent", "vaulting", "slackly", "pasteurizes", "goody", "pearls", "conceptualization", "fins", "brogues",
         "muskogee", "naziism", "stromboli", "sunflower", "tosca", "luridness", "booing", "zaniness", "creel",
         "bootblacks", "attendants", "swordplay", "impinging", "premiere", "sedimentation", "traffickers", "carrel",
         "observatories", "telltales", "cuckolded", "ampler", "alternately", "shovel", "tasmania", "whooping",
         "methodologies", "pickling", "overseer", "sunnier", "sanchez", "supervening", "viscus", "cramped", "santayana",
         "utopias", "intimated", "pianists", "computerizing", "interpolating", "reggie", "horseshoe", "preeminent",
         "qantas", "standish", "flagpoles", "thievery", "admiring", "palefaces", "overflows", "gaea", "monique",
         "sheepskin", "bestiaries", "beethoven", "fleming", "convalescing", "moldier", "snobby", "jewry", "hoodwinking",
         "hope", "henri", "listlessly", "doggoning", "anointed", "notable", "talented", "uric", "towards", "flue",
         "arbitrated", "ingredients", "academy", "clutches", "novelle", "parallelling", "confabbed", "synthesized",
         "frontally", "underexpose", "ulcerates", "injuring", "stimulant", "catalytic", "ogle", "throatily", "ions",
         "chores", "spyglasses", "metabolic", "statesmanlike", "tingles", "ossifies", "forge", "coiffing", "transepts",
         "autopsy", "colorfast", "winery", "procyon", "sequesters", "amended", "putted", "huff", "fliers", "harpooning",
         "protecting", "shipboard", "dwindled", "collations", "stonewalls", "criticism", "thigh", "quarried",
         "knelling", "knitted", "redeemable", "berm", "seventy", "misguides", "schlemiel", "pawn", "ineligibility",
         "lathe", "bosses", "temperance", "haywire", "everglade", "confections", "gruelings", "mindful", "paracelsus",
         "quarreled", "furtively", "airdropped", "clodhopper", "transmuting", "whilst", "moldavia", "exploiting",
         "chicories", "unrolling", "shorthand", "antigens", "satirically", "earner", "primmer", "jolly", "perch",
         "nonplussing", "circulars", "hanks", "fingerprinted", "syllogism", "adulate", "nominally", "telecasted",
         "quelled", "accustoming", "backslide", "culminates", "spiraled", "compactor", "gatorade", "cornballs",
         "investor", "cupboards", "deign", "induced", "ewe", "snoopers", "supposed", "glitters", "overlie",
         "ambassadorial", "chancel", "accumulations", "strictest", "thalami", "shops", "moos", "applicators", "corncob",
         "dona", "apostrophes", "kibitzes", "rinses", "kemerovo", "confide", "clemenceau", "centenarians",
         "memorialized", "windburn", "nominate", "obscene", "equivocations", "arts", "karloff", "projected", "scorned",
         "limping", "lava", "sanitaria", "clementine", "brandies", "unionize", "compacted", "griming", "trilogies",
         "babysit", "congas", "glittery", "pimientos", "phototypesetter", "multivitamin", "carbohydrates", "lode",
         "photographs", "iniquity", "micrometer", "freemasonry", "burros", "marchers", "percentiles", "werewolf",
         "weightlifting", "valedictories", "gacrux", "senselessly", "stoppage", "monolithic", "handy", "overspent",
         "nymphomaniac", "seasick", "misogynistic", "coltrane", "coeval", "inversion", "darkliest", "landfills",
         "barbers", "suppurate", "cavern", "submerge", "illumination", "hesitates", "lashes", "covenants", "thomism",
         "aneurism", "disappointed", "gnarls", "sprint", "abash", "frightens", "undoings", "pa", "helicopters",
         "reexamines", "vassal", "blessing", "devaluation", "purports", "urinals", "adjudged", "garaging", "pacific",
         "infomercials", "whitewashed", "fawned", "baptisms", "concede", "cornflakes", "fostered", "clewed", "tiller",
         "dalmatians", "signification", "boneless", "chunkiness", "omar", "paramedicals", "professor", "unionizing",
         "scripted", "anchors", "tabloid", "alton", "redrafted", "reflexive", "luddite", "lamb", "bidirectional",
         "seaports", "christendom", "gets", "chaperoning", "tchaikovsky", "wasters", "dioxin", "nuke", "apologized",
         "queasily", "fujiwara", "prearranges", "abdul", "upraising", "sparklers", "signposting", "comparison", "sb",
         "cherokees", "ungentlemanly", "typing", "waisted", "sputter", "biographers", "waltz", "stanches",
         "upbringings", "smithereens", "tutor", "young", "eloy", "sourdoughs", "clingier", "hoisting", "blazon",
         "homosexuality", "lorries", "kippering", "abacus", "specks", "congressional", "auditing", "lash", "eternal",
         "carve", "facade", "defrauds", "neighbored", "musses", "dismount", "lope", "lawbreaker", "deed", "japes",
         "repeal", "factorization", "impetuosity", "sitters", "disorganizing", "fussing", "vale", "epitomized",
         "executrixes", "deprivations", "woodcarvings", "miscalls", "skateboard", "pedicured", "cloakroom", "vassaled",
         "innumerable", "knelt", "cellulose", "beams", "uniform", "metatarsals", "meteorologist", "column", "burnishes",
         "dentists", "quids", "toasts", "tableland", "archivist", "gladiolas", "replica", "lording", "viewed",
         "polisher", "trooping", "indistinctly", "resisters", "flycatchers", "toughed", "regor", "insolvent", "ninnies",
         "truckled", "birthplaces", "telescopic", "abelson", "puritanism", "leanings", "disturbingly", "transmission",
         "mortify", "upshot", "newlywed", "adam", "ballplayer", "lockwood", "quirking", "blocs", "theatre",
         "palliatives", "smudges", "marvelled", "ramble", "offside", "indissoluble", "droplets", "fencing", "hubbard",
         "estimation", "incorrect", "malarial", "confucian", "games", "sacraments", "trivets", "gammas", "nastiest",
         "merrymakers", "sealskin", "overkilled", "bosser", "strafe", "exclusives", "bouldered", "antiwar",
         "guitarists", "jerry", "earthly", "oscilloscope", "edmonton", "merger", "laminated", "surmountable",
         "casually", "backspaced", "charcoals", "overheating", "caramel", "oldened", "asterisked", "tun", "peafowl",
         "purplest", "skippering", "prep", "congregating", "glaringly", "crummiest", "noreen", "bromide",
         "nomenclatures", "kristin", "purportedly", "vamoosing", "busybody", "crucify", "capote", "milliners", "veils",
         "windsurf", "reconnecting", "layering", "ossified", "noble", "tiptoeing", "smiles", "swain", "perihelion",
         "bagels", "obfuscation", "spreadsheets", "buddy", "flints", "planting", "hogwarts", "abusers", "welfare",
         "mouses", "lament", "auras", "unrelieved", "cougars", "cattails", "chubby", "handstands", "woolly",
         "concealment", "mediterraneans", "judas", "electrocardiographs", "skulks", "puttered", "crimean", "liven",
         "odds", "warehousing", "lifeguard", "deepness", "clowns", "blossomed", "constriction", "honest", "noisemakers",
         "whist", "overcame", "sulphured", "vertebras", "commiseration", "jolted", "adjourns", "bungles", "sonnies",
         "housekeeper", "buddha", "bolsters", "warlords", "banjarmasin", "militated", "anywheres", "lula", "weirdos",
         "raymond", "sections", "taoisms", "pay", "latest", "bights", "carousel", "sups", "lavatory", "conciser", "lon",
         "beefburger", "clinically", "snakes", "backslash", "developmental", "squibb", "smote", "mastectomy", "genius",
         "sallying", "niagara", "guild", "altai", "ascetics", "marts", "misbehaved", "desired", "pagodas", "platypus",
         "freemen", "lovemaking", "transfers", "brewing", "absorbents", "unions", "lite", "wilder", "popovers",
         "yamaha", "faultier", "supplements", "forsythia", "rummy", "propagation", "motorbikes", "velez",
         "unequivocally", "lend", "silliness", "idiosyncratic", "disseminated", "carter", "washed", "dizzying",
         "bedsore", "pawned", "lr", "nubile", "galloped", "subservience", "marlin", "chance", "schooners", "faction",
         "clutters", "transmits", "weathercocks", "illustrations", "quell", "senegalese", "touchiest", "psychs",
         "joshes", "shallots", "garrottes", "coifs", "glaswegian", "hydrated", "smirch", "strutting", "arnold",
         "coughing", "tangier", "olympics", "overexposing", "benefactor", "reputably", "snootier", "smuggles", "bogus",
         "priories", "chandra", "diplomatics", "muskrat", "forbad", "monasticism", "outshone", "farewell", "thomas",
         "epaulets", "nectarines", "affording", "buckles", "concordance", "lebesgue", "pawed", "lackey", "sweden",
         "confirmatory", "humble", "wizards", "controlling", "scoffing", "worthy", "homely", "lexical", "batteries",
         "chorusing", "inboard", "cotton", "lustrous", "devalued", "herbart", "travestied", "veneered", "maxillas",
         "omelet", "ptarmigans", "alnilam", "submerging", "bucks", "niceties", "yong", "gender", "toileting", "biding",
         "caffeine", "lubricant", "dashikis", "balm", "filings", "series", "paraguayan", "fatefully", "craggier",
         "oversexed", "milkweed", "passels", "concretely", "rapiers", "channeled", "multifaceted", "tenth",
         "conflagration", "pivoted", "horribles", "tugs", "fireman", "hull", "semifinalist", "odorous", "carats",
         "uncomfortably", "clappers", "chaffinches", "demagnetize", "limits", "ups", "wimp", "reserved", "busyness",
         "illuminate", "autocratic", "zips", "sculley", "vainest", "conciliators", "vacillations", "daughter", "beau",
         "stashes", "mini", "shallow", "divided", "invert", "caesurae", "vibrantly", "germination", "winching",
         "curmudgeon", "hurts", "battens", "lovable", "redistricted", "neighing", "nonexistence", "foghorns",
         "manifesting", "retrofitting", "fictitious", "gracefully", "shetlands", "transistors", "rectitude", "shea",
         "acquisitions", "predetermines", "huts", "blintze", "cortland", "murdered", "leninism", "ninetieths",
         "fractal", "inveighs", "compelled", "ringer", "mistiest", "snorting", "transportation", "dictionaries",
         "khyber", "misspelling", "bifocal", "playmates", "disputant", "neuters", "epidemics", "vijayawada", "ambles",
         "splashdowns", "cants", "bandannas", "millennia", "glows", "fowled", "cupped", "laramie", "occupied",
         "gelatine", "scorches", "sidelights", "beagling", "campused", "doer", "gunfighting", "tsitsihar", "marin",
         "fireside", "yellow", "seagram", "strap", "arrivals", "sixty", "lipscomb", "wares", "awfullest", "servants",
         "dreamer", "crockery", "mahavira", "brad", "outpourings", "dusty", "shrubs", "briefest", "segments",
         "cartilages", "excommunicated", "generator", "placket", "berate", "emulations", "suspicious", "fortnights",
         "sped", "griding", "panting", "trimaran", "suspend", "retract", "adversity", "regimental", "hammett",
         "wallflower", "tyrannize", "cinemascope", "ambassador", "humerus", "litter", "trying", "sinkable", "descents",
         "coveralls", "region", "landslid", "bowed", "zigzagging", "upholstery", "parch", "scratchy", "altitude",
         "angling", "scaldings", "plussed", "babel", "cirrus", "haberdasher", "gayle", "chillest", "catboat",
         "battling", "bellini", "extincts", "appendices", "unmade", "footstool", "deaths", "secretively", "erasmus",
         "agra", "soothsayers", "stillest", "despoils", "affiliated", "mumble", "aleut", "gyp", "purchased", "kory",
         "cesspool", "interacted", "demarcates", "fanciness", "defines", "absorbed", "fireplugs", "pluckiest",
         "misstates", "grenades", "untidiness", "ventricles", "overexpose", "dryad", "tumbler", "chengdu",
         "thistledown", "dork", "unauthorized", "holmes", "downgrading", "syphilises", "trammelled", "sending",
         "afflict", "ornithologist", "serried", "much", "emoluments", "wilfully", "strayed", "canada", "dachshund",
         "compost", "glamorized", "gerrymandering", "senate", "allots", "arsonists", "coloratura", "borderlines",
         "cartooned", "evert", "continents", "profiteers", "merritt", "cyclical", "quickens", "funkier", "dourer",
         "salmonellae", "seemingly", "cheeky", "showering", "proses", "imperturbably", "gush", "intolerable", "wozniak",
         "vegetables", "neglectful", "aesculapius", "whimsicality", "unfolds", "conceited", "junkyards", "immanent",
         "norbert", "pollsters", "ruse", "gymnosperms", "toothbrush", "accommodate", "multitudinous", "blessedest",
         "squeezers", "portal", "newspaperwoman", "polytheistic", "affectioning", "rhiannon", "holing", "johanna",
         "gregariousness", "fishtail", "tainting", "wasteful", "aeneas", "flycatcher", "salem", "ventilator", "sat",
         "hiroshima", "breed", "housewarming", "migrate", "smocking", "plethora", "fathead", "mussy", "communion",
         "foxhole", "renters", "telecommunications", "obtusest", "puncture", "preparing", "encyclopaedias", "footholds",
         "violets", "megalomaniac", "dakotas", "accentuating", "joanna", "gentleman", "dardanelles", "aeration",
         "gerrymander", "liker", "chatters", "questioningly", "guesswork", "lunar", "upgrading", "mara", "consultancy",
         "sanguines", "sunks", "polyethylene", "injected", "aneurysms", "caterwaul", "eventfully", "aquariums", "yowl",
         "valeria", "suicides", "emptiness", "pajamas", "uphill", "myles", "playfully", "palestine", "agape", "chichi",
         "vatican", "exponentiation", "shipper", "planes", "reprints", "dieters", "involving", "dimwitted", "cranach",
         "homestretch", "fitfully", "fluoridation", "esthetics", "coworkers", "cannibalize", "lipids", "heartsick",
         "flatware", "rage", "hazier", "overburdening", "psychosis", "wage", "debasements", "personalized", "itaipu",
         "valletta", "rhythm", "cyclic", "hillocks", "badlands", "proffer", "cretin", "sexuality", "hefts",
         "rehabilitate", "disfranchisement", "skews", "rundowns", "unrolls", "dividing", "boomerang", "gigglier",
         "respects", "layette", "heads", "devised", "franny", "therapists", "ballsy", "inkier", "passer", "capone",
         "housebreak", "rachel", "portered", "palpate", "bugles", "marionettes", "werewolves", "primitive", "powerboat",
         "polio", "wylie", "industrial", "convenes", "sweep", "wear", "peaks", "trudging", "manuring", "yttrium",
         "hometown", "graving", "latency", "warrant", "tinsmiths", "preheats", "withered", "priestley", "dipper",
         "overtakes", "thurber", "softwood", "renounced", "turfed", "immensely", "pilgrim", "neophyte", "mendicant",
         "trampolining", "detachable", "corralling", "haydn", "victimizing", "pockmarks", "goya", "triumphs", "sleet",
         "whiplashes", "inconsistent", "slaked", "handled", "nissan", "housecleaned", "gentling", "alexandra",
         "dallying", "kiddos", "rayleigh", "oxen", "boarders", "demonstrator", "mollusk", "micawber", "earthshaking",
         "burials", "consecration", "algeria", "sinister", "bloodcurdling", "garrotted", "byte", "dungeon", "ferrets",
         "trunk", "finery", "dodos", "staid", "champagnes", "gelt", "hedonists", "barrier", "trikes", "lock", "scaly",
         "hibernation", "lopsidedly", "snake", "ellison", "runabout", "rhapsodizing", "divinity", "bugged",
         "entomological", "kazoo", "powdered", "smeared", "shoestring", "knocker", "galbraith", "clomp", "rudders",
         "infused", "sale", "silicone", "underfoot", "chirruped", "beatific", "preached", "commingles", "enchanters",
         "nonflammable", "vacillating", "autistic", "uganda", "intruding", "expatiating", "coddles", "attendant",
         "races", "paying", "confuting", "guyed", "expanded", "tolstoy", "contestants", "judd", "comediennes", "pansy",
         "upstage", "schoolmistresses", "lesion", "rollback", "rapt", "sicked", "locomotion", "flint", "interactions",
         "vaginae", "intonation", "comedic", "totaled", "sickles", "immensities", "leastwise", "brothers", "rinking",
         "worksheet", "impending", "mussed", "reinterpretation", "backtrack", "thrummed", "devastate", "plaiding",
         "accusatory", "rafts", "stew", "infringe", "impulses", "shuffleboard", "decaffeinates", "marquez", "milksop",
         "artisan", "attlee", "decide", "italic", "catalyst", "squeamish", "transmuted", "coffer", "sadness", "forays",
         "slipperier", "bella", "dandy", "singletons", "inflating", "pittance", "shearer", "spilling", "acid",
         "mortgager", "proverbs", "wily", "headwinds", "murmured", "humidified", "cramping", "herrick", "phoneticians",
         "boas", "bucksaw", "play", "falters", "overbites", "dill", "renovators", "mush", "clockworks", "diaspora",
         "favorites", "stomachaches", "flinch", "boston", "scrounges", "hubert", "utters", "million", "weekended",
         "touchdown", "reactor", "postcards", "brown", "snide", "banjoist", "recourse", "deuced", "scurrying",
         "chihuahuas", "abutments", "proliferate", "carillonned", "saucier", "kaposi", "amanda", "fillet",
         "demographics", "eldon", "skyed", "abut", "bernadette", "downplays", "alluvia", "trappers", "insofar",
         "breathlessness", "insistently", "imitative", "cede", "embargoed", "boisterousness", "edicts", "braise",
         "impacted", "ukrainian", "lankiest", "bounden", "trilling", "pinnate", "unconvincing", "kent", "indulging",
         "stagnant", "piston", "cookery", "commits", "caucasoid", "fronds", "bootless", "clustered", "giggled",
         "lugubriousness", "intents", "elms", "boorishly", "stalemate", "blaine", "proportionality", "sampson",
         "ethnologists", "francisco", "headmistress", "propel", "knapsack", "misapplied", "ensnare", "subtotal",
         "intersected", "maud", "shooing", "pouts", "messed", "schmidt", "liberated", "continuations", "impossible",
         "unsatisfied", "flanneling", "unscrupulous", "comity", "scopes", "incised", "venial", "takes", "auction",
         "bashfully", "bremen", "televangelists", "eyesight", "ineptness", "hecate", "sweller", "carrot", "presidency",
         "hook", "nerveless", "mastication", "abstractnesses", "precognition", "indent", "sombre", "fieriness",
         "quiescent", "indispositions", "shiftiness", "caveatted", "gulps", "best", "spread", "chews",
         "prevaricating"]))
